- id: license-eye
  name: license-eye
  additional_dependencies:
    - github.com/apache/skywalking-eyes/cmd/license-eye@latest
  entry: license-eye header fix --verbosity error
  language: golang
  pass_filenames: false
